matrix:
  include:
    - language: java
      jdk: oraclejdk12
      before_script:
        - cd server

    - language: node_js
      node_js:
        - 12
      cache:
        directories:
          - node_modules
      before_script:
        - cd client
      script:
        - npm run test:unit
