matrix:
  include:
    - before_script:
        - cd server
      language: java
      jdk: oraclejdk12
      cache:
        directories:
          - $HOME/.m2

    - language: node_js
      node_js:
        - 12
      install:
        - cd client
        - npm install
      script:
        - npm run test:unit
      cache:
        directories:
          - $HOME/.npm
          - $TRAVIS_BUILD_DIR/client/node_modules
          - $TRAVIS_BUILD_DIR/client/.cache
